version: "3.7"

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - digital-wallet

    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - digital-wallet

    mysql:
        container_name: mysql
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - ${FORWARD_DB_PORT:-3306}:3306
        networks:
            - digital-wallet

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        logging:
            driver: 'none'
        ports:
            - "${FORWARD_MAILHOG_PORT:-1025}:1025"
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
        networks:
            - digital-wallet

    queue:
        container_name: queue
        image: laravel9-app
        restart: unless-stopped
        command: "php artisan queue:listen"
        volumes:
            - ./:/var/www
        depends_on:
            - app
        networks:
            - digital-wallet

networks:
    digital-wallet:
        driver: bridge
